package com.socket.tcp;

import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.net.UnknownHostException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class TCP_Server extends Thread {
   private ServerSocket serverSocket;
   
   //Initialize Server Socket with port no and timeout
   public TCP_Server(int port) throws IOException {
      serverSocket = new ServerSocket(port);
      serverSocket.setSoTimeout(100000);
   }

   public void run() {
	   String res = "";
      while(true) {
         try {
            System.out.println("Waiting for client on port " + 
               serverSocket.getLocalPort() + "...");
            
            Socket server = serverSocket.accept();
            System.out.println("Connected to " + server.getRemoteSocketAddress());
            
            //Object to receive info from client
            DataInputStream in = new DataInputStream(server.getInputStream());
            
            System.out.println("Recieved following data from client");
            String ip1,ip2,mask;
            ip1 = in.readUTF();
            ip2 = in.readUTF();
            mask = in.readUTF();
            System.out.println(ip1+"\n"+ip2+"\n"+mask+"\n");
            
            //Check whether the two IP Addresses belong to the same network
            //Convert the ip addresses to byte array
            //if IpAddress1 AND SubnetMask = IpAddress AND SubnetMask
            //then they belong to same network
            //else different network
            try {
     			byte[] a1 = InetAddress.getByName(ip1).getAddress();
     		    byte[] a2 = InetAddress.getByName(ip2).getAddress();
     		    byte[] m = InetAddress.getByName(mask).getAddress();
     	
     		    boolean flag = false;
     		    for (int i = 0; i < a1.length; i++)
     		        if ((a1[i] & m[i]) != (a2[i] & m[i])) {
     		        	flag = true;
     		        	res = "The IP Addresses "+ip1+" and "+ip2+
     		        		  " belong to different network";
     		        }
     		    if(flag == false)
     		    	res = "The IP Addresses "+ip1+" and "+ip2+
	        		  		" belong to same network";
     		}catch(UnknownHostException e) {
     			System.out.println("Incorrect IPs");
     		} 
           
            //Object to send info to client
            DataOutputStream out = new DataOutputStream(server.getOutputStream());
            System.out.println("Sending following result to client:\n"+res);
            out.writeUTF(res);
            server.close();
            
         }catch(SocketTimeoutException s) {
            System.out.println("Socket timed out!");
            break;
         }catch(IOException e) {
            e.printStackTrace();
            break;
         }
      }
   }
   
   public static void main(String [] args) {
	  //Port no generated by server to which the client can connect
      int port = 6760;
      try {
    	 //Create thread object to start the server
         Thread t = new TCP_Server(port);
         t.start();
      }catch(IOException e) {
         e.printStackTrace();
      }
   }
}